Repository flutter/cocoon, pull requests merged in 2021-11, with the labels that each got.

#1427 [release_dashboard] Create Conductor service
  release_dashboard/analysis_options.yaml
  release_dashboard/lib/main.dart
  release_dashboard/lib/services/conductor.dart
  release_dashboard/lib/services/local_conductor.dart
  release_dashboard/lib/widgets/conductor_status.dart
  release_dashboard/lib/widgets/progression.dart
  release_dashboard/pubspec.lock
  release_dashboard/test/main_test.dart
  release_dashboard/test/src/services/fake_conductor.dart
  release_dashboard/test/widgets/conductor_status_test.dart
  release_dashboard/test/widgets/stepper_test.dart
Labels: waiting for tree to go green, cla: yes

#1431 removed path from conductor status test
  release_dashboard/test/widgets/conductor_status_test.dart
Labels: waiting for tree to go green, cla: yes

#1433 Update provision_salt.sh
  dev/provision_salt.sh
Labels: waiting for tree to go green, cla: yes

#1414 [app_dart] Fallback to git-on-borg for source files
  app_dart/bin/generate_jspb.dart
  app_dart/bin/validate_task_ownership.dart
  app_dart/integration_test/common.dart
  app_dart/integration_test/validate_all_ci_configs_test.dart
  app_dart/integration_test/validate_test_ownership_test.dart
  app_dart/lib/src/foundation/utils.dart
  app_dart/lib/src/service/scheduler.dart
  app_dart/test/foundation/utils_test.dart
Labels: waiting for tree to go green, cla: yes

#1416 [Conductor] Added clean confirmation prompt on conductor status
  release_dashboard/lib/main.dart
  release_dashboard/lib/widgets/common/dialog_prompt.dart
  release_dashboard/lib/widgets/conductor_status.dart
  release_dashboard/pubspec.lock
  release_dashboard/test/widgets/common/dialog_prompt_test.dart
Labels: waiting for tree to go green, cla: yes

#1437 Use staging data when auto deflake tests
  app_dart/lib/src/service/bigquery.dart
  app_dart/test/service/bigquery_test.dart
Labels: waiting for tree to go green, cla: yes

#1439 File flaky issue with limited number of successful builds
  app_dart/lib/src/request_handlers/flaky_handler_utils.dart
  app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart
  app_dart/test/request_handlers/file_flaky_issue_and_pr_test_data.dart
Labels: waiting for tree to go green, cla: yes

#1438 added flutter_lint
  release_dashboard/analysis_options.yaml
  release_dashboard/lib/main.dart
  release_dashboard/lib/services/local_conductor.dart
  release_dashboard/lib/widgets/conductor_status.dart
  release_dashboard/pubspec.lock
  release_dashboard/pubspec.yaml
Labels: waiting for tree to go green, cla: yes

#1442 Enable test check for packages and plugins repos
  app_dart/lib/src/request_handlers/github_webhook.dart
  app_dart/test/request_handlers/github_webhook_test.dart
  app_dart/test/src/datastore/fake_config.dart
Labels: waiting for tree to go green, cla: yes

#1441 Skip PR creation when a flaky bug exists and is open or closed recently
  app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart
  app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart
Labels: waiting for tree to go green, cla: yes

#1443 link "an exemption" to the wiki
  app_dart/lib/src/service/config.dart
Labels: waiting for tree to go green, cla: yes

#1419 [Conductor] status into state provider
  release_dashboard/lib/main.dart
  release_dashboard/lib/state/status_state.dart
  release_dashboard/lib/widgets/conductor_status.dart
  release_dashboard/lib/widgets/progression.dart
  release_dashboard/pubspec.lock
  release_dashboard/pubspec.yaml
  release_dashboard/test/main_test.dart
  release_dashboard/test/src/services/fake_conductor.dart
  release_dashboard/test/widgets/conductor_status_test.dart
  release_dashboard/test/widgets/stepper_test.dart
Labels: waiting for tree to go green, cla: yes

#1432 [app_dart] Fix GitHub check retries
  app_dart/lib/src/foundation/github_checks_util.dart
  app_dart/lib/src/model/github/checks.dart
  app_dart/lib/src/model/github/checks.g.dart
  app_dart/lib/src/model/luci/buildbucket.g.dart
  app_dart/lib/src/model/luci/push_message.g.dart
  app_dart/lib/src/request_handlers/github_webhook.dart
  app_dart/lib/src/service/github_checks_service.dart
  app_dart/lib/src/service/luci_build_service.dart
  app_dart/lib/src/service/scheduler.dart
  app_dart/pubspec.lock
  app_dart/pubspec.yaml
  app_dart/test/request_handlers/github_webhook_test.dart
  app_dart/test/request_handlers/reset_try_task_test.dart
  app_dart/test/service/github_checks_service_test.dart
  app_dart/test/service/luci_build_service_test.dart
  app_dart/test/service/scheduler_test.dart
  app_dart/test/src/utilities/mocks.mocks.dart
Labels: waiting for tree to go green, cla: yes

#1430 [conductor] added URL launcher
  release_dashboard/lib/widgets/common/url_button.dart
  release_dashboard/lib/widgets/conductor_status.dart
  release_dashboard/macos/Flutter/Flutter-Debug.xcconfig
  release_dashboard/macos/Flutter/Flutter-Release.xcconfig
  release_dashboard/macos/Flutter/GeneratedPluginRegistrant.swift
  release_dashboard/macos/Podfile
  release_dashboard/macos/Podfile.lock
  release_dashboard/macos/Runner.xcodeproj/project.pbxproj
  release_dashboard/macos/Runner.xcworkspace/contents.xcworkspacedata
  release_dashboard/pubspec.lock
  release_dashboard/pubspec.yaml
  release_dashboard/test/widgets/common/url_button_test.dart
  release_dashboard/test/widgets/conductor_status_test.dart
Labels: waiting for tree to go green, cla: yes

#1423 added validators
  release_dashboard/lib/logic/git.dart
  release_dashboard/lib/widgets/create_release_substeps.dart
  release_dashboard/test/logic/git_test.dart
  release_dashboard/test/widgets/create_release_substeps_test.dart
  release_dashboard/test/widgets/stepper_test.dart
Labels: waiting for tree to go green, cla: yes

#1444 Don't request tests for some commment-only changes
  app_dart/lib/src/request_handlers/github_webhook.dart
  app_dart/test/request_handlers/github_webhook_test.dart
Labels: waiting for tree to go green, cla: yes

#1451 Revert "Remove cocoon mirroring from main to master."
  .github/workflows/mirror.yml
Labels: cla: yes

#1446 [scheduler] Pass ci.yaml properties to buildbucket
  app_dart/lib/src/foundation/utils.dart
  app_dart/lib/src/model/ci_yaml/target.dart
  app_dart/lib/src/service/luci_build_service.dart
  app_dart/lib/src/service/scheduler.dart
  app_dart/test/foundation/utils_test.dart
  app_dart/test/service/github_checks_service_test.dart
  app_dart/test/service/luci_build_service_test.dart
  app_dart/test/service/scheduler_test.dart
  app_dart/test/src/utilities/entity_generators.dart
  app_dart/test/src/utilities/mocks.mocks.dart
Labels: cla: yes, warning: land on red to fix tree breakage

#1454 [app_dart] Allow waiting for green to accept empty statuses
  app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
  app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart
  app_dart/lib/src/service/config.dart
  app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Labels: cla: yes

#1452 [conductor] Fixed enums naming
  release_dashboard/lib/widgets/conductor_status.dart
  release_dashboard/lib/widgets/create_release_substeps.dart
  release_dashboard/test/widgets/create_release_substeps_test.dart
Labels: waiting for tree to go green, cla: yes

#1447 Kill adb server before running any device healthcheck
  device_doctor/lib/src/android_device.dart
  device_doctor/lib/src/utils.dart
  device_doctor/test/src/android_device_test.dart
Labels: waiting for tree to go green, cla: yes

#1456 [app_dart] Fix GraphQL parameters
  app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart
Labels: cla: yes

#1450 [conductor] Conductor Clean Error Message
  release_dashboard/lib/main.dart
  release_dashboard/lib/widgets/clean_release_button.dart
  release_dashboard/lib/widgets/common/snackbar_prompt.dart
  release_dashboard/test/widgets/clean_release_button_test.dart
  release_dashboard/test/widgets/common/snackbar_prompt_test.dart
Labels: waiting for tree to go green, cla: yes

#1453 [device doctor] Add android device battery health check
  device_doctor/lib/src/android_device.dart
  device_doctor/lib/src/utils.dart
  device_doctor/test/src/android_device_test.dart
Labels: waiting for tree to go green, cla: yes

#1448 [conductor] Step 2 refactor
  release_dashboard/lib/widgets/common/checkbox_substep.dart
  release_dashboard/lib/widgets/engine_cherrypicks_substeps.dart
  release_dashboard/lib/widgets/progression.dart
  release_dashboard/test/widgets/common/checkbox_substep_test.dart
  release_dashboard/test/widgets/engine_cherrypicks_substeps_test.dart
Labels: waiting for tree to go green, cla: yes

#1449 Conductor delete error msg
  release_dashboard/test/main_test.dart
Labels: waiting for tree to go green, cla: yes

#1455 Use a fixed number of commits when calculating flaky percentage
  app_dart/lib/src/service/bigquery.dart
  app_dart/test/src/utilities/mocks.mocks.dart
Labels: waiting for tree to go green, cla: yes

#1457 [ci.yaml] Add postsubmit_properties, update dependency docs
  CI_YAML.md
  app_dart/lib/src/model/proto/internal/scheduler.proto
Labels: waiting for tree to go green, cla: yes

#1458 [conductor] Removed URL padding
  release_dashboard/lib/widgets/common/url_button.dart
Labels: waiting for tree to go green, cla: yes

#1382 Calculate engine tree status using commits from main.
  app_dart/lib/src/request_handlers/push_build_status_to_github.dart
Labels: waiting for tree to go green, cla: yes

#1460 [app_dart] Allow main branch as base
  app_dart/lib/src/request_handlers/github_webhook.dart
  app_dart/lib/src/service/config.dart
  app_dart/test/src/datastore/fake_config.dart
Labels: waiting for tree to go green, cla: yes

#1462 [device doctor] Check ios revoked cert
  device_doctor/lib/src/ios_device.dart
  device_doctor/test/src/ios_device_test.dart
Labels: waiting for tree to go green, cla: yes

#1464 Use correct bucket stats when file/update flaky bugs
  app_dart/lib/src/request_handlers/flaky_handler_utils.dart
  app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart
  app_dart/lib/src/service/bigquery.dart
  app_dart/test/request_handlers/update_existing_flaky_issues_test.dart
  app_dart/test/request_handlers/update_existing_flaky_issues_test_data.dart
  app_dart/test/src/utilities/mocks.mocks.dart
Labels: waiting for tree to go green, cla: yes

#1465 Calculate tree status from both master and main.
  app_dart/lib/src/service/build_status_provider.dart
Labels: waiting for tree to go green, cla: yes

#1469 Remove use of primaryBrightnessColor.
  dashboard/lib/widgets/app_bar.dart
Labels: waiting for tree to go green, cla: yes

#1471 Use main as default branch when pushing tree status.
  app_dart/lib/src/request_handlers/push_build_status_to_github.dart
Labels: waiting for tree to go green, cla: yes

#1459 [release_dashboard] Add substeps for engine cherrypicks step
  release_dashboard/analysis_options.yaml
  release_dashboard/lib/main.dart
  release_dashboard/lib/services/conductor.dart
  release_dashboard/lib/services/local_conductor.dart
  release_dashboard/lib/state/status_state.dart
  release_dashboard/lib/widgets/clean_release_button.dart
  release_dashboard/lib/widgets/common/checkbox_substep.dart
  release_dashboard/lib/widgets/conductor_status.dart
  release_dashboard/lib/widgets/create_release_substeps.dart
  release_dashboard/lib/widgets/engine_cherrypicks_substeps.dart
  release_dashboard/lib/widgets/progression.dart
  release_dashboard/test/fake_process_manager.dart
  release_dashboard/test/fake_process_manager_test.dart
  release_dashboard/test/src/services/fake_conductor.dart
  release_dashboard/test/src/test_state_generator.dart
  release_dashboard/test/widgets/conductor_status_test.dart
  release_dashboard/test/widgets/engine_cherrypicks_substeps_test.dart
Labels: waiting for tree to go green, cla: yes

#1461 Script to migrate open pull requests to main
  dev/prs_to_main.sh
Labels: waiting for tree to go green, cla: yes

#1474 Update device doctor build script to use dart compile exe
  device_doctor/tool/build.bat
  device_doctor/tool/build.sh
Labels: waiting for tree to go green, cla: yes

#1475 Keep only one backend version in serving state.
  cloud_build/deploy.sh
Labels: cla: yes

#1463 Adjust integration test labelling
  app_dart/lib/src/request_handlers/github_webhook.dart
  app_dart/test/request_handlers/github_webhook_test.dart
Labels: waiting for tree to go green, cla: yes

#1478 [scheduler] Retry ci.yaml checks
  app_dart/lib/src/service/scheduler.dart
  app_dart/test/service/scheduler_test.dart
Labels: waiting for tree to go green, cla: yes, warning: land on red to fix tree breakage

#1476 [release_dashboard] StatusState keys string to enums
  release_dashboard/lib/models/cherrypick.dart
  release_dashboard/lib/models/conductor_status.dart
  release_dashboard/lib/state/status_state.dart
  release_dashboard/lib/widgets/conductor_status.dart
  release_dashboard/lib/widgets/engine_cherrypicks_substeps.dart
  release_dashboard/test/widgets/conductor_status_test.dart
Labels: waiting for tree to go green, cla: yes

#1466 [release_dashboard] Add substeps for `Codesign Engine binaries` step
  release_dashboard/lib/widgets/clean_release_button.dart
  release_dashboard/lib/widgets/codesign_engine_substeps.dart
  release_dashboard/lib/widgets/common/url_button.dart
  release_dashboard/lib/widgets/conductor_status.dart
  release_dashboard/lib/widgets/create_release_substeps.dart
  release_dashboard/lib/widgets/engine_cherrypicks_substeps.dart
  release_dashboard/lib/widgets/progression.dart
  release_dashboard/test/widgets/codesign_engine_substeps_test.dart
Labels: waiting for tree to go green, cla: yes

#1480 [app_dart] Roll pubspec versions
  app_dart/pubspec.lock
  app_dart/pubspec.yaml
Labels: waiting for tree to go green, cla: yes

#1481 Clean up github token for test flaky bot
  app_dart/lib/src/service/config.dart
  app_dart/test/src/datastore/fake_config.dart
Labels: waiting for tree to go green, cla: yes

#1468 [ci.yaml] Support branch regexes
  CI_YAML.md
  app_dart/integration_test/validate_all_ci_configs_test.dart
  app_dart/lib/src/model/ci_yaml/ci_yaml.dart
  app_dart/lib/src/service/scheduler.dart
  app_dart/pubspec.lock
  app_dart/pubspec.yaml
  app_dart/test/model/ci_yaml/ci_yaml_test.dart
  app_dart/test/service/scheduler_test.dart
Labels: waiting for tree to go green, cla: yes

#1472 [release_conductor] add dialogue prompt with input confirmation
  release_dashboard/lib/widgets/clean_release_button.dart
  release_dashboard/lib/widgets/common/dialog_prompt.dart
  release_dashboard/lib/widgets/common/snackbar_prompt.dart
  release_dashboard/test/widgets/clean_release_button_test.dart
  release_dashboard/test/widgets/common/dialog_prompt_test.dart
Labels: waiting for tree to go green, cla: yes

#1489 Updating salt minion to 3002.7 for macs
  dev/provision_salt.sh
Labels: waiting for tree to go green, cla: yes
