Repository flutter/cocoon, pull requests merged in 2021-04, with the labels that each got.

#1138 [app_dart] Update engine build status to use config value
  app_dart/lib/src/datastore/config.dart
  app_dart/lib/src/request_handlers/push_engine_status_to_github.dart
Labels: waiting for tree to go green

#1140 Add additional engine auto-labelling
  app_dart/lib/src/request_handlers/github_webhook.dart
  app_dart/test/request_handlers/github_webhook_test.dart
Labels: enhancement

#1144 [scheduler] Add scheduler field to target
  app_dart/lib/src/model/proto/internal/scheduler.pb.dart
  app_dart/lib/src/model/proto/internal/scheduler.pbenum.dart
  app_dart/lib/src/model/proto/internal/scheduler.pbjson.dart
  app_dart/lib/src/model/proto/internal/scheduler.proto
  app_dart/test/service/scheduler_test.dart
Labels: waiting for tree to go green

#1149 Test all repo configs
  app_dart/integration_test/common.dart
  app_dart/integration_test/validate_all_ci_configs_test.dart
  app_dart/lib/cocoon_service.dart
  app_dart/pubspec.lock
  test_utilities/bin/dart_test_runner.sh
Labels: waiting for tree to go green

#1151 [app_dart] Fix null http provider in scheduler
  app_dart/lib/src/service/scheduler.dart
Labels: waiting for tree to go green

#1153 Add a composite index for flutter repo and creation date on Checklist.
  app_dart/index.yaml
Labels: waiting for tree to go green

#1154 [app_dart] Add waiting for tree to go green on flutter/packages
  app_dart/lib/src/datastore/config.dart
  app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
  app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Labels: waiting for tree to go green

#1156 add presubmit, postsubmit to targets
  app_dart/README.md
  app_dart/analysis_options.yaml
  app_dart/lib/src/model/proto/internal/scheduler.pb.dart
  app_dart/lib/src/model/proto/internal/scheduler.pbenum.dart
  app_dart/lib/src/model/proto/internal/scheduler.pbjson.dart
  app_dart/lib/src/model/proto/internal/scheduler.proto
Labels: cla: yes, waiting for tree to go green

#1150 [app_dart] Differentiate 404s from other HTTP exceptions on GitHub files
  app_dart/bin/server.dart
  app_dart/bin/validate_scheduler_config.dart
  app_dart/integration_test/validate_all_ci_configs_test.dart
  app_dart/lib/src/datastore/config.dart
  app_dart/lib/src/foundation/utils.dart
  app_dart/lib/src/service/scheduler.dart
  app_dart/test/foundation/utils_test.dart
  app_dart/test/service/scheduler_test.dart
  app_dart/test/src/service/fake_scheduler.dart
Labels: waiting for tree to go green

#1158 [app_dart] Lower log warning to debug in auth flow
  app_dart/lib/src/request_handling/authentication.dart
  app_dart/test/request_handling/authentication_test.dart
Labels: cla: yes, waiting for tree to go green

#1155 Prevent failures on empty status list.
  app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
  app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
  app_dart/test/src/datastore/fake_config.dart
Labels: cla: yes, waiting for tree to go green

#1159 Revert "fix dartfmt"
  app_flutter/lib/widgets/progress_button.dart
  app_flutter/lib/widgets/task_overlay.dart
Labels: cla: yes, waiting for tree to go green

#1160 Ensure milo can find builds triggered by cocoon backend.
  app_dart/lib/src/service/luci_build_service.dart
Labels: cla: yes, waiting for tree to go green

#1157 [app_dart] Vaccum github commits
  app_dart/bin/server.dart
  app_dart/cron.yaml
  app_dart/lib/cocoon_service.dart
  app_dart/lib/src/datastore/config.dart
  app_dart/lib/src/request_handlers/refresh_github_commits.dart
  app_dart/lib/src/request_handlers/vacuum_github_commits.dart
  app_dart/lib/src/service/scheduler.dart
  app_dart/test/request_handlers/vacuum_github_commits_test.dart
  app_dart/test/src/datastore/fake_config.dart
  app_flutter/lib/build_dashboard_page.dart
  app_flutter/lib/service/appengine_cocoon.dart
  app_flutter/lib/service/cocoon.dart
  app_flutter/lib/service/dev_cocoon.dart
  app_flutter/lib/state/build.dart
  app_flutter/test/build_dashboard_page_test.dart
  app_flutter/test/service/appengine_cocoon_test.dart
Labels: cla: yes, waiting for tree to go green

#1163 Update README.md
  README.md
Labels: cla: yes, waiting for tree to go green

#1161 add 2.2.x branch to build dashboard
  app_dart/dev/branches.txt
Labels: cla: yes, waiting for tree to go green

#1162 [app_dart] Refactor presubmit logic to scheduler
  app_dart/bin/server.dart
  app_dart/lib/src/request_handlers/github_webhook.dart
  app_dart/lib/src/request_handlers/reset_try_task.dart
  app_dart/lib/src/service/github_checks_service.dart
  app_dart/lib/src/service/scheduler.dart
  app_dart/test/request_handlers/github_webhook_test.dart
  app_dart/test/request_handlers/reset_try_task_test.dart
  app_dart/test/service/github_checks_service_test.dart
  app_dart/test/service/scheduler_test.dart
  app_dart/test/src/service/fake_buildbucket.dart
  app_dart/test/src/service/fake_luci_build_service.dart
  app_dart/test/src/service/fake_scheduler.dart
Labels: cla: yes, waiting for tree to go green

#1165 Prevent retries on tasks already scheduled or running.
  app_dart/lib/src/request_handlers/reset_prod_task.dart
  app_dart/lib/src/request_handling/exceptions.dart
  app_dart/lib/src/service/luci_build_service.dart
  app_dart/test/request_handlers/reset_prod_task_test.dart
  app_dart/test/service/luci_build_service_test.dart
  app_flutter/lib/service/appengine_cocoon.dart
Labels: cla: yes, waiting for tree to go green

#1164 [app_dart] Refactor repo references to RepositorySlug
  app_dart/lib/src/datastore/config.dart
  app_dart/lib/src/foundation/github_checks_util.dart
  app_dart/lib/src/model/appengine/commit.dart
  app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
  app_dart/lib/src/request_handlers/github_rate_limit_status.dart
  app_dart/lib/src/request_handlers/github_webhook.dart
  app_dart/lib/src/request_handlers/push_build_status_to_github.dart
  app_dart/lib/src/request_handlers/push_engine_status_to_github.dart
  app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
  app_dart/lib/src/request_handlers/refresh_chromebot_status.dart
  app_dart/lib/src/request_handlers/reset_prod_task.dart
  app_dart/lib/src/request_handlers/vacuum_github_commits.dart
  app_dart/lib/src/service/github_checks_service.dart
  app_dart/lib/src/service/github_status_service.dart
  app_dart/lib/src/service/luci.dart
  app_dart/lib/src/service/luci_build_service.dart
  app_dart/lib/src/service/scheduler.dart
  app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
  app_dart/test/request_handlers/github_webhook_test.dart
  app_dart/test/request_handlers/push_engine_status_to_github_test.dart
  app_dart/test/request_handlers/refresh_chromebot_status_test.dart
  app_dart/test/request_handlers/reset_devicelab_task_test.dart
  app_dart/test/request_handlers/reset_prod_task_test.dart
  app_dart/test/request_handlers/reset_try_task_test.dart
  app_dart/test/service/luci_test.dart
  app_dart/test/src/datastore/fake_config.dart
Labels: cla: yes, waiting for tree to go green

#1171 Add functionality to retry engine builds using curl commands.
  app_dart/lib/src/request_handlers/reset_prod_task.dart
  app_dart/test/request_handlers/reset_prod_task_test.dart
Labels: cla: yes

#1168 Removing Agent client code
  agent/README.md
  agent/analysis_options.yaml
  agent/bin/agent.dart
  agent/bin/ci.sh
  agent/bin/smoke_test.sh
  agent/config.sample.yaml
  agent/lib/src/adb.dart
  agent/lib/src/agent.dart
  agent/lib/src/commands/ci.dart
  agent/lib/src/commands/run.dart
  agent/lib/src/health.dart
  agent/lib/src/list_processes.dart
  agent/lib/src/runner.dart
  agent/lib/src/utils.dart
  agent/pubspec.lock
  agent/pubspec.yaml
  agent/test/src/adb_test.dart
  agent/test/src/health_test.dart
  agent/test/src/utils_test.dart
  agent/tool/infra-dialog/.gitignore
  agent/tool/infra-dialog/infra-dialog.xcodeproj/project.pbxproj
  agent/tool/infra-dialog/infra-dialog.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  agent/tool/infra-dialog/infra-dialog.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  agent/tool/infra-dialog/infra-dialog.xcodeproj/xcshareddata/xcschemes/infra-dialog.xcscheme
  agent/tool/infra-dialog/infra-dialogUITests/Info.plist
  agent/tool/infra-dialog/infra-dialogUITests/infra_dialogUITests.swift
Labels: cla: yes, waiting for tree to go green

#1169 Remove agent code from app_flutter
  app_dart/lib/src/request_handlers/update_agent_health_history.dart
  app_flutter/USER_GUIDE.md
  app_flutter/lib/agent_dashboard_page.dart
  app_flutter/lib/logic/agent_health_details.dart
  app_flutter/lib/logic/links.dart
  app_flutter/lib/main.dart
  app_flutter/lib/service/appengine_cocoon.dart
  app_flutter/lib/service/cocoon.dart
  app_flutter/lib/service/dev_cocoon.dart
  app_flutter/lib/state/agent.dart
  app_flutter/lib/widgets/agent_health_details_bar.dart
  app_flutter/lib/widgets/agent_list.dart
  app_flutter/lib/widgets/agent_tile.dart
  app_flutter/lib/widgets/state_provider.dart
  app_flutter/lib/widgets/task_overlay.dart
  app_flutter/test/agent_dashboard_page_test.dart
  app_flutter/test/goldens/build_dashboard.defaultPropertySheet.dark.png
  app_flutter/test/goldens/build_dashboard.defaultPropertySheet.png
  app_flutter/test/index_page_test.dart
  app_flutter/test/logic/agent_health_details_test.dart
  app_flutter/test/navigation_drawer_test.dart
  app_flutter/test/service/appengine_cocoon_test.dart
  app_flutter/test/service/dev_cocoon_test.dart
  app_flutter/test/state/agent_test.dart
  app_flutter/test/utils/fake_agent_state.dart
  app_flutter/test/utils/mocks.dart
  app_flutter/test/utils/wrapper.dart
  app_flutter/test/widgets/agent_health_details_bar_test.dart
  app_flutter/test/widgets/agent_list_test.dart
  app_flutter/test/widgets/agent_tile_test.dart
  app_flutter/test/widgets/goldens/task_overlay_test.flaky_overlay_open.png
  app_flutter/test/widgets/goldens/task_overlay_test.normal_overlay_open.png
  app_flutter/test/widgets/task_overlay_test.dart
Labels: cla: yes, waiting for tree to go green

#1172 Revert "Remove agent code from app_flutter"
  app_dart/lib/src/request_handlers/update_agent_health_history.dart
  app_flutter/USER_GUIDE.md
  app_flutter/lib/agent_dashboard_page.dart
  app_flutter/lib/logic/agent_health_details.dart
  app_flutter/lib/logic/links.dart
  app_flutter/lib/main.dart
  app_flutter/lib/service/appengine_cocoon.dart
  app_flutter/lib/service/cocoon.dart
  app_flutter/lib/service/dev_cocoon.dart
  app_flutter/lib/state/agent.dart
  app_flutter/lib/widgets/agent_health_details_bar.dart
  app_flutter/lib/widgets/agent_list.dart
  app_flutter/lib/widgets/agent_tile.dart
  app_flutter/lib/widgets/state_provider.dart
  app_flutter/lib/widgets/task_overlay.dart
  app_flutter/test/agent_dashboard_page_test.dart
  app_flutter/test/goldens/build_dashboard.defaultPropertySheet.dark.png
  app_flutter/test/goldens/build_dashboard.defaultPropertySheet.png
  app_flutter/test/index_page_test.dart
  app_flutter/test/logic/agent_health_details_test.dart
  app_flutter/test/navigation_drawer_test.dart
  app_flutter/test/service/appengine_cocoon_test.dart
  app_flutter/test/service/dev_cocoon_test.dart
  app_flutter/test/state/agent_test.dart
  app_flutter/test/utils/fake_agent_state.dart
  app_flutter/test/utils/mocks.dart
  app_flutter/test/utils/wrapper.dart
  app_flutter/test/widgets/agent_health_details_bar_test.dart
  app_flutter/test/widgets/agent_list_test.dart
  app_flutter/test/widgets/agent_tile_test.dart
  app_flutter/test/widgets/goldens/task_overlay_test.flaky_overlay_open.png
  app_flutter/test/widgets/goldens/task_overlay_test.normal_overlay_open.png
  app_flutter/test/widgets/task_overlay_test.dart
Labels: cla: yes, waiting for tree to go green

#1173 Revert "Removing Agent client code"
  agent/README.md
  agent/analysis_options.yaml
  agent/bin/agent.dart
  agent/bin/ci.sh
  agent/bin/smoke_test.sh
  agent/config.sample.yaml
  agent/lib/src/adb.dart
  agent/lib/src/agent.dart
  agent/lib/src/commands/ci.dart
  agent/lib/src/commands/run.dart
  agent/lib/src/health.dart
  agent/lib/src/list_processes.dart
  agent/lib/src/runner.dart
  agent/lib/src/utils.dart
  agent/pubspec.lock
  agent/pubspec.yaml
  agent/test/src/adb_test.dart
  agent/test/src/health_test.dart
  agent/test/src/utils_test.dart
  agent/tool/infra-dialog/.gitignore
  agent/tool/infra-dialog/infra-dialog.xcodeproj/project.pbxproj
  agent/tool/infra-dialog/infra-dialog.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  agent/tool/infra-dialog/infra-dialog.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  agent/tool/infra-dialog/infra-dialog.xcodeproj/xcshareddata/xcschemes/infra-dialog.xcscheme
  agent/tool/infra-dialog/infra-dialogUITests/Info.plist
  agent/tool/infra-dialog/infra-dialogUITests/infra_dialogUITests.swift
Labels: cla: yes

#1176 [app_dart] Fix vacuum github commits on empty list
  app_dart/lib/src/request_handlers/vacuum_github_commits.dart
  app_dart/test/request_handlers/vacuum_github_commits_test.dart
Labels: cla: yes, waiting for tree to go green

#1177 [app_dart] Upgrade dart test to a recent version
  app_dart/pubspec.lock
  app_dart/pubspec.yaml
Labels: cla: yes, waiting for tree to go green

#1178 Adds a graphql query service.
  app_dart/bin/server.dart
  app_dart/lib/cocoon_service.dart
  app_dart/lib/src/request_handlers/query_github_graphql.dart
  app_dart/test/request_handlers/query_github_graphql_test.dart
Labels: cla: yes, waiting for tree to go green

#1174 Revert "Revert "Remove agent code from app_flutter""
  app_dart/lib/src/request_handlers/update_agent_health_history.dart
  app_flutter/USER_GUIDE.md
  app_flutter/lib/agent_dashboard_page.dart
  app_flutter/lib/logic/agent_health_details.dart
  app_flutter/lib/logic/links.dart
  app_flutter/lib/main.dart
  app_flutter/lib/service/appengine_cocoon.dart
  app_flutter/lib/service/cocoon.dart
  app_flutter/lib/service/dev_cocoon.dart
  app_flutter/lib/state/agent.dart
  app_flutter/lib/widgets/agent_health_details_bar.dart
  app_flutter/lib/widgets/agent_list.dart
  app_flutter/lib/widgets/agent_tile.dart
  app_flutter/lib/widgets/state_provider.dart
  app_flutter/lib/widgets/task_overlay.dart
  app_flutter/test/agent_dashboard_page_test.dart
  app_flutter/test/goldens/build_dashboard.defaultPropertySheet.dark.png
  app_flutter/test/goldens/build_dashboard.defaultPropertySheet.png
  app_flutter/test/index_page_test.dart
  app_flutter/test/logic/agent_health_details_test.dart
  app_flutter/test/navigation_drawer_test.dart
  app_flutter/test/service/appengine_cocoon_test.dart
  app_flutter/test/service/dev_cocoon_test.dart
  app_flutter/test/state/agent_test.dart
  app_flutter/test/utils/fake_agent_state.dart
  app_flutter/test/utils/mocks.dart
  app_flutter/test/utils/wrapper.dart
  app_flutter/test/widgets/agent_health_details_bar_test.dart
  app_flutter/test/widgets/agent_list_test.dart
  app_flutter/test/widgets/agent_tile_test.dart
  app_flutter/test/widgets/goldens/task_overlay_test.flaky_overlay_open.png
  app_flutter/test/widgets/goldens/task_overlay_test.normal_overlay_open.png
  app_flutter/test/widgets/task_overlay_test.dart
Labels: cla: yes, waiting for tree to go green

#1175 Revert "Revert "Removing Agent client code""
  agent/README.md
  agent/analysis_options.yaml
  agent/bin/agent.dart
  agent/bin/ci.sh
  agent/bin/smoke_test.sh
  agent/config.sample.yaml
  agent/lib/src/adb.dart
  agent/lib/src/agent.dart
  agent/lib/src/commands/ci.dart
  agent/lib/src/commands/run.dart
  agent/lib/src/health.dart
  agent/lib/src/list_processes.dart
  agent/lib/src/runner.dart
  agent/lib/src/utils.dart
  agent/pubspec.lock
  agent/pubspec.yaml
  agent/test/src/adb_test.dart
  agent/test/src/health_test.dart
  agent/test/src/utils_test.dart
  agent/tool/infra-dialog/.gitignore
  agent/tool/infra-dialog/infra-dialog.xcodeproj/project.pbxproj
  agent/tool/infra-dialog/infra-dialog.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  agent/tool/infra-dialog/infra-dialog.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  agent/tool/infra-dialog/infra-dialog.xcodeproj/xcshareddata/xcschemes/infra-dialog.xcscheme
  agent/tool/infra-dialog/infra-dialogUITests/Info.plist
  agent/tool/infra-dialog/infra-dialogUITests/infra_dialogUITests.swift
Labels: cla: yes, waiting for tree to go green

#1170 Remove agent health update cron job.
  app_dart/cron.yaml
Labels: cla: yes, waiting for tree to go green

#1179 [app_dart] Update readiness check to match Dart
  app_dart/app.yaml
Labels: cla: yes, waiting for tree to go green

#1181 Replaced accentColor with colorScheme.secondary
  repo_dashboard/lib/repository.dart
Labels: cla: yes, waiting for tree to go green

#1183 Update imports to match the latest directives_ordering analyzer check
  app_flutter/README.md
  app_flutter/ios/Flutter/Debug.xcconfig
  app_flutter/ios/Flutter/Release.xcconfig
  app_flutter/lib/logic/qualified_task.dart
  app_flutter/lib/logic/task_grid_filter.dart
  app_flutter/lib/state/build.dart
  app_flutter/lib/widgets/commit_author_avatar.dart
  app_flutter/lib/widgets/commit_box.dart
  app_flutter/lib/widgets/lattice.dart
  app_flutter/lib/widgets/luci_task_attempt_summary.dart
  app_flutter/lib/widgets/task_attempt_summary.dart
  app_flutter/lib/widgets/task_grid.dart
  app_flutter/macos/Flutter/Flutter-Debug.xcconfig
  app_flutter/macos/Flutter/Flutter-Release.xcconfig
  app_flutter/pubspec.lock
  app_flutter/test/build_dashboard_page_test.dart
  app_flutter/test/logic/qualified_task_test.dart
  app_flutter/test/logic/task_grid_filter_test.dart
  app_flutter/test/service/downloader_web_test.dart
  app_flutter/test/service/google_authentication_test.dart
  app_flutter/test/state/flutter_build_test.dart
  app_flutter/test/state/index_test.dart
  app_flutter/test/utils/fake_build.dart
  app_flutter/test/utils/fake_index_state.dart
  app_flutter/test/widgets/accessibility_test.dart
  app_flutter/test/widgets/commit_author_avatar_test.dart
  app_flutter/test/widgets/commit_box_test.dart
  app_flutter/test/widgets/luci_task_attempt_summary_test.dart
  app_flutter/test/widgets/sign_in_button_test.dart
  app_flutter/test/widgets/task_attempt_summary_test.dart
  app_flutter/test/widgets/task_grid_test.dart
  app_flutter/test/widgets/task_icon_test.dart
  app_flutter/test/widgets/web_image_test.dart
Labels: cla: yes, waiting for tree to go green

#1182 Remove agent code from app_dart (phase 1)
  README.md
  app_dart/bin/server.dart
  app_dart/lib/cocoon_service.dart
  app_dart/lib/src/request_handlers/append_log.dart
  app_dart/lib/src/request_handlers/authorize_agent.dart
  app_dart/lib/src/request_handlers/create_agent.dart
  app_dart/lib/src/request_handlers/get_log.dart
  app_dart/lib/src/request_handlers/get_status.dart
  app_dart/lib/src/request_handlers/reserve_task.dart
  app_dart/lib/src/request_handlers/reset_devicelab_task.dart
  app_dart/lib/src/request_handlers/update_agent_health.dart
  app_dart/lib/src/request_handlers/update_agent_health_history.dart
  app_dart/lib/src/request_handlers/vacuum-clean.dart
  app_dart/lib/src/service/reservation_provider.dart
  app_dart/test/request_handlers/append_log_test.dart
  app_dart/test/request_handlers/authorize_agent_test.dart
  app_dart/test/request_handlers/create_agent_test.dart
  app_dart/test/request_handlers/get_status_test.dart
  app_dart/test/request_handlers/reserve_task_test.dart
  app_dart/test/request_handlers/reset_devicelab_task_test.dart
  app_dart/test/request_handlers/update_agent_health_history_test.dart
  app_dart/test/request_handlers/update_agent_health_test.dart
  app_dart/test/request_handlers/vacuum_clean_test.dart
  app_dart/test/service/reservation_provider_test.dart
  app_dart/test/src/utilities/mocks.dart
  app_flutter/test/utils/appengine_cocoon_test_data.dart
Labels: cla: yes, waiting for tree to go green

#1185 [app_dart] Remove devicelab manifest scheduling
  app_dart/lib/src/model/devicelab/manifest.dart
  app_dart/lib/src/model/devicelab/manifest.g.dart
  app_dart/lib/src/service/scheduler.dart
  app_dart/test/request_handlers/vacuum_github_commits_test.dart
  app_dart/test/service/scheduler_test.dart
  app_dart/test/src/service/fake_scheduler.dart
Labels: cla: yes, waiting for tree to go green

#1186 Fix duplicates tasknames get status list
  app_dart/lib/src/service/build_status_provider.dart
  app_dart/test/service/build_status_provider_test.dart
Labels: cla: yes, waiting for tree to go green

#1187 Removing agent references from authentication code in app_dart
  app_dart/lib/src/model/appengine/allowed_account.dart
  app_dart/lib/src/request_handling/authentication.dart
  app_dart/lib/src/request_handling/swarming_authentication.dart
  app_dart/test/request_handling/api_request_handler_test.dart
  app_dart/test/request_handling/authentication_test.dart
  app_dart/test/request_handling/swarming_authentication_test.dart
  app_dart/test/src/request_handling/fake_authentication.dart
Labels: cla: yes, waiting for tree to go green

#1189 Removing agent proto and classes from app_dart
  app_dart/lib/src/model/appengine/agent.dart
  app_dart/lib/src/model/appengine/agent.g.dart
  app_dart/lib/src/model/appengine/key_helper.dart
  app_dart/lib/src/model/proto/internal/agent.pb.dart
  app_dart/lib/src/model/proto/internal/agent.proto
  app_dart/lib/src/model/proto/protos.dart
  app_dart/lib/src/request_handlers/update_task_status.dart
  app_dart/lib/src/service/agent_service.dart
  app_dart/lib/src/service/task_provider.dart
  app_dart/test/model/agent_test.dart
  app_dart/test/request_handlers/update_task_status_test.dart
  app_dart/test/service/task_provider_test.dart
  app_dart/test/src/utilities/mocks.dart
Labels: cla: yes, waiting for tree to go green

#1188 Show distinctive icons on dashboard for different builder types
  app_flutter/assets/cirrus.png
  app_flutter/assets/iphone.png
  app_flutter/assets/linux.png
  app_flutter/lib/widgets/task_icon.dart
  app_flutter/test/goldens/build_dashboard.defaultPropertySheet.dark.png
  app_flutter/test/goldens/build_dashboard.defaultPropertySheet.png
  app_flutter/test/widgets/goldens/task_grid_test.dev.origin.dark.png
  app_flutter/test/widgets/goldens/task_grid_test.dev.origin.png
  app_flutter/test/widgets/goldens/task_overlay_test.flaky_overlay_closed.png
  app_flutter/test/widgets/goldens/task_overlay_test.flaky_overlay_open.png
  app_flutter/test/widgets/goldens/task_overlay_test.nondevicelab_closed.png
  app_flutter/test/widgets/goldens/task_overlay_test.nondevicelab_open.png
  app_flutter/test/widgets/goldens/task_overlay_test.normal_overlay_closed.png
  app_flutter/test/widgets/goldens/task_overlay_test.normal_overlay_open.png
  app_flutter/test/widgets/task_icon_test.dart
Labels: cla: yes, waiting for tree to go green
