Repository flutter/cocoon, pull requests merged in 2021-09, with the labels that each got.

#1343 Remove the use of devicelab service account.
  app_dart/bin/server.dart
  app_dart/lib/src/request_handlers/update_task_status.dart
  app_dart/lib/src/request_handling/swarming_authentication.dart
  app_dart/lib/src/service/access_client_provider.dart
  app_dart/lib/src/service/access_token_provider.dart
  app_dart/lib/src/service/buildbucket.dart
  app_dart/lib/src/service/config.dart
  app_dart/lib/src/service/luci_build_service.dart
  app_dart/test/request_handlers/github_webhook_test.dart
  app_dart/test/service/buildbucket_test.dart
  app_dart/test/service/luci_build_service_test.dart
  app_dart/test/src/datastore/fake_config.dart
  app_dart/test/src/service/fake_luci_build_service.dart
  app_dart/test/src/utilities/mocks.dart
  device_doctor/test/src/utils.dart
Labels: waiting for tree to go green, cla: yes

#1345 [ci.yaml] Add documentation about properties
  CI_YAML.md
Labels: waiting for tree to go green, cla: yes

#1344 Prepare search requests considering realm when calling builderbucket API
  app_dart/lib/src/model/luci/buildbucket.dart
  app_dart/lib/src/request_handlers/push_build_status_to_github.dart
  app_dart/lib/src/request_handlers/refresh_chromebot_status.dart
  app_dart/lib/src/service/luci.dart
  app_dart/test/service/luci_test.dart
Labels: waiting for tree to go green, cla: yes

#1347 Revert "Prepare search requests considering realm when calling builderbucket API"
  app_dart/lib/src/model/luci/buildbucket.dart
  app_dart/lib/src/model/proto/internal/scheduler.pb.dart
  app_dart/lib/src/request_handlers/push_build_status_to_github.dart
  app_dart/lib/src/request_handlers/refresh_chromebot_status.dart
  app_dart/lib/src/service/luci.dart
  app_dart/test/service/luci_test.dart
Labels: cla: yes

#1353 Enable workflow to mirror master branch to main.
  .github/workflows/mirror.yml
Labels: cla: yes

#1355 Grant explicit write permissions.
  .github/workflows/mirror.yml
Labels: cla: yes

#1356 Use githubbot token instead of the default one.
  .github/workflows/mirror.yml
Labels: cla: yes

#1358 Update master references to main
  .ci.yaml
  app_dart/README.md
Labels: cla: yes

#1359 [app_dart] Truncate luci build push messages before sending as check
  app_dart/lib/src/service/github_checks_service.dart
  app_dart/test/service/github_checks_service_test.dart
Labels: waiting for tree to go green, cla: yes

#1346 Fix vacuum handler.
  app_dart/lib/src/request_handlers/vacuum_github_commits.dart
Labels: waiting for tree to go green, cla: yes

#1348 Create checks and batch build requests asynchronously.
  app_dart/lib/src/request_handlers/push_build_status_to_github.dart
  app_dart/lib/src/request_handlers/query_github_graphql.dart
  app_dart/lib/src/request_handlers/reset_prod_task.dart
  app_dart/lib/src/request_handlers/reset_try_task.dart
  app_dart/lib/src/service/config.dart
  app_dart/lib/src/service/github_checks_service.dart
  app_dart/lib/src/service/github_service.dart
  app_dart/lib/src/service/luci.dart
  app_dart/lib/src/service/luci_build_service.dart
  app_dart/lib/src/service/scheduler.dart
  app_dart/test/request_handlers/github_webhook_test.dart
  app_dart/test/request_handlers/luci_status_test.dart
  app_dart/test/request_handling/static_file_handler_test.dart
  app_dart/test/service/luci_build_service_test.dart
  app_dart/test/service/scheduler_test.dart
  app_dart/test/src/datastore/fake_config.dart
  app_dart/test/src/service/fake_github_service.dart
  app_dart/test/src/service/fake_graphql_client.dart
Labels: waiting for tree to go green, cla: yes

#1350 Update gold endpoint
  app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
  app_dart/test/request_handlers/push_gold_status_to_github_test.dart
Labels: bug, waiting for tree to go green, cla: yes

#1357 Reorder branch replication to replicate from main to master.
  .github/workflows/mirror.yml
Labels: waiting for tree to go green, cla: yes

#1351 Update bot label and test logic
  app_dart/lib/src/request_handlers/github_webhook.dart
  app_dart/test/request_handlers/github_webhook_test.dart
Labels: waiting for tree to go green, cla: yes

#1362 [app_dart] Switch to logging singleton
  app_dart/bin/server.dart
  app_dart/integration_test/common.dart
  app_dart/integration_test/validate_all_ci_configs_test.dart
  app_dart/lib/src/foundation/typedefs.dart
  app_dart/lib/src/foundation/utils.dart
  app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
  app_dart/lib/src/request_handlers/github_rate_limit_status.dart
  app_dart/lib/src/request_handlers/github_webhook.dart
  app_dart/lib/src/request_handlers/luci_status.dart
  app_dart/lib/src/request_handlers/push_build_status_to_github.dart
  app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
  app_dart/lib/src/request_handlers/query_github_graphql.dart
  app_dart/lib/src/request_handlers/refresh_chromebot_status.dart
  app_dart/lib/src/request_handlers/refresh_cirrus_status.dart
  app_dart/lib/src/request_handlers/reset_prod_task.dart
  app_dart/lib/src/request_handlers/reset_try_task.dart
  app_dart/lib/src/request_handlers/update_task_status.dart
  app_dart/lib/src/request_handlers/vacuum_github_commits.dart
  app_dart/lib/src/request_handling/authentication.dart
  app_dart/lib/src/request_handling/request_handler.dart
  app_dart/lib/src/request_handling/swarming_authentication.dart
  app_dart/lib/src/service/build_status_provider.dart
  app_dart/lib/src/service/config.dart
  app_dart/lib/src/service/github_checks_service.dart
  app_dart/lib/src/service/github_service.dart
  app_dart/lib/src/service/logging.dart
  app_dart/lib/src/service/luci_build_service.dart
  app_dart/lib/src/service/scheduler.dart
  app_dart/test/foundation/utils_test.dart
  app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
  app_dart/test/request_handlers/luci_status_test.dart
  app_dart/test/request_handlers/push_gold_status_to_github_test.dart
  app_dart/test/request_handling/api_request_handler_test.dart
  app_dart/test/request_handling/authentication_test.dart
  app_dart/test/request_handling/request_handler_test.dart
  app_dart/test/request_handling/swarming_authentication_test.dart
  app_dart/test/service/github_checks_service_test.dart
  app_dart/test/service/luci_build_service_test.dart
  app_dart/test/service/scheduler_test.dart
  app_dart/test/src/request_handling/api_request_handler_tester.dart
  app_dart/test/src/request_handling/fake_authentication.dart
  app_dart/test/src/request_handling/fake_logging.dart
  app_dart/test/src/request_handling/no_auth_request_handler_tester.dart
  app_dart/test/src/request_handling/request_handler_tester.dart
  app_dart/test/src/service/fake_build_status_provider.dart
  app_dart/test/src/service/fake_github_service.dart
  app_dart/test/src/service/fake_scheduler.dart
  app_dart/test/src/utilities/mocks.mocks.dart
  licenses/check_licenses.dart
  licenses/pubspec.lock
  licenses/pubspec.yaml
  test_utilities/bin/prepare_environment.sh
Labels: waiting for tree to go green, cla: yes

#1360 [app_dart] Log ci.yaml exceptions
  app_dart/lib/src/service/scheduler.dart
Labels: waiting for tree to go green, cla: yes

#1363 Fix scheduling problems.
  app_dart/lib/src/model/luci/buildbucket.dart
  app_dart/lib/src/model/luci/buildbucket.g.dart
  app_dart/lib/src/service/luci_build_service.dart
  app_dart/test/service/buildbucket_test.dart
  app_dart/test/service/luci_build_service_test.dart
  app_dart/test/src/utilities/mocks.mocks.dart
Labels: waiting for tree to go green, cla: yes

#1364 [app_dart] Re-enable github endpoint
  app_dart/cron.yaml
  app_dart/pubspec.lock
Labels: waiting for tree to go green, cla: yes

#1365 [app_dart] Update frob service account
  app_dart/lib/src/service/config.dart
Labels: waiting for tree to go green, cla: yes

#1366 Remove autogenerated files and add them to gitignore.
  dashboard/.gitignore
  dashboard/linux/flutter/generated_plugin_registrant.cc
  dashboard/linux/flutter/generated_plugin_registrant.h
  dashboard/windows/flutter/generated_plugin_registrant.cc
  dashboard/windows/flutter/generated_plugin_registrant.h
Labels: waiting for tree to go green, cla: yes

#1367 Fixes build re-run failing with a 400 status code.
  app_dart/lib/src/service/luci_build_service.dart
Labels: waiting for tree to go green, cla: yes

#1368 Do not try to submit if PR is not mergeable.
  app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
  app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Labels: cla: yes

#1369 [app_dart] Log all writes
  app_dart/lib/src/service/logging.dart
Labels: waiting for tree to go green, cla: yes

#1371 Remove `web` as an indicator of golden file test execution
  app_dart/lib/src/request_handlers/push_gold_status_to_github.dart
  app_dart/test/request_handlers/push_gold_status_to_github_test.dart
Labels: bug, waiting for tree to go green, cla: yes

#1373 Add additional logging to validate mergeable state.
  app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
Labels: cla: yes

#1352 Makes the get existing pr until function throw more descriptive error
  app_dart/lib/src/request_handlers/flaky_handler_utils.dart
  app_dart/test/request_handlers/flaky_handler_utiles_test.dart
Labels: waiting for tree to go green, cla: yes

#1370 Add screen on check for android devices
  device_doctor/lib/src/android_device.dart
  device_doctor/lib/src/utils.dart
  device_doctor/test/src/android_device_test.dart
Labels: waiting for tree to go green, cla: yes

#1372 Revert "Do not try to submit if PR is not mergeable."
  app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
  app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Labels: waiting for tree to go green, cla: yes
