Repository flutter/cocoon, pull requests merged in 2022-05, with the labels that each got.

#1788 Pin Dockerfile Dependencies
  app_dart/Dockerfile
  auto_submit/Dockerfile
Labels: waiting for tree to go green

#1809 Move auto-submit to dart official images.
  auto_submit/.dockerignore
  auto_submit/Dockerfile
  auto_submit/app.yaml
  auto_submit/bin/server.dart
  auto_submit/lib/requests/readiness_check.dart
  auto_submit/lib/service/config.dart
Labels: waiting for tree to go green

#1812 Migrate app_dart application to dart official docker images.
  app_dart/.gitignore
  app_dart/Dockerfile
Labels: waiting for tree to go green

#1813 Adds logic to deal with duplicated messages and closed PRs.
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/test/requests/check_pull_request_test.dart
  auto_submit/test/requests/github_webhook_test_data.dart
Labels: autosubmit

#1814 Update package:graphql to 5.1.1
  app_dart/pubspec.lock
  app_dart/pubspec.yaml
  app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
  app_dart/test/request_handlers/push_gold_status_to_github_test.dart
  app_dart/test/request_handlers/query_github_graphql_test.dart
  app_dart/test/src/service/fake_graphql_client.dart
  app_dart/test/src/utilities/mocks.mocks.dart
  auto_submit/pubspec.lock
  auto_submit/pubspec.yaml
  auto_submit/test/requests/check_pull_request_test.dart
  auto_submit/test/src/service/fake_graphql_client.dart
Labels: autosubmit

#1815 Impeller was merged into engine so removing impeller repos
  app_dart/lib/src/service/config.dart
  app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
  app_dart/test/request_handlers/vacuum_github_commits_test.dart
Labels: autosubmit

#1816 Revert "[scheduler] Process build messages with null task key (#1698)"
  app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
  app_dart/lib/src/service/scheduler.dart
  app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
  app_dart/test/src/utilities/push_message.dart
Labels: autosubmit

#1785 Improve flutter-gold pending message
  app_dart/lib/src/service/config.dart
Labels: waiting for tree to go green, autosubmit

#1818 checkboxes for stages were being ignored when set to default again
  dashboard/lib/build_dashboard_page.dart
Labels: waiting for tree to go green

#1817 Adding a filter for staging tasks
  dashboard/lib/logic/task_grid_filter.dart
  dashboard/test/logic/task_grid_filter_test.dart
Labels: waiting for tree to go green

#1695 [release] update release branches through cron jobs, and retrieve release branches for frontend display
  app_dart/bin/server.dart
  app_dart/lib/cocoon_service.dart
  app_dart/lib/src/model/appengine/branch.dart
  app_dart/lib/src/request_handlers/get_branches.dart
  app_dart/lib/src/request_handlers/update_branches.dart
  app_dart/lib/src/service/datastore.dart
  app_dart/pubspec.lock
  app_dart/pubspec.yaml
  app_dart/test/request_handlers/get_branches_test.dart
  app_dart/test/request_handlers/get_repos_test.dart
  app_dart/test/request_handlers/update_branches_test.dart
  app_dart/test/src/service/fake_scheduler.dart
  app_dart/test/src/utilities/mocks.dart
  app_dart/test/src/utilities/mocks.mocks.dart
  cron.yaml
  dashboard/lib/build_dashboard_page.dart
  dashboard/lib/model/branch.pb.dart
  dashboard/lib/model/branch.pbenum.dart
  dashboard/lib/model/branch.pbjson.dart
  dashboard/lib/model/branch.pbserver.dart
  dashboard/lib/model/branch.proto
  dashboard/lib/service/appengine_cocoon.dart
  dashboard/lib/service/cocoon.dart
  dashboard/lib/service/dev_cocoon.dart
  dashboard/lib/state/build.dart
  dashboard/test/build_dashboard_page_test.dart
  dashboard/test/navigation_drawer_test.dart
  dashboard/test/service/appengine_cocoon_test.dart
  dashboard/test/state/build_test.dart
  dashboard/test/utils/appengine_cocoon_test_data.dart
  dashboard/test/utils/fake_build.dart
  dashboard/test/utils/mocks.mocks.dart
Labels: autosubmit

#1819 adding try catch to processMerge function
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/test/requests/check_pull_request_test.dart
Labels: autosubmit

#1821 Reland "[scheduler] Process build messages with null task key (#1698)"
  app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
  app_dart/lib/src/service/scheduler.dart
  app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
  app_dart/test/src/utilities/push_message.dart
Labels: autosubmit

#1826 [app_dart] Move release approvals to fluttergithubbot
  app_dart/lib/src/request_handlers/github_webhook.dart
Labels: autosubmit

#1829 neutral status shouldn't stop PR from landing.
  app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
  app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/test/requests/check_pull_request_test.dart
  auto_submit/test/requests/github_webhook_test_data.dart
Labels: autosubmit

#1830 [dashboard] change json return type from map to array
  dashboard/lib/service/appengine_cocoon.dart
  dashboard/lib/state/build.dart
  dashboard/test/utils/appengine_cocoon_test_data.dart
Labels: autosubmit

#1832 [app_dart] Remove branches.txt
  app_dart/README.md
  app_dart/dev/branches.txt
Labels: autosubmit

#1831 [release] exclude forks for branch datastore
  app_dart/lib/src/service/branch_service.dart
  app_dart/test/service/branch_service_test.dart
  app_dart/test/src/utilities/webhook_generators.dart
Labels: autosubmit

#1833 removing hardcode true in BoolFilterProperty.
  dashboard/lib/widgets/filter_property_sheet.dart
  dashboard/test/logic/task_grid_filter_test.dart
Labels: autosubmit

#1828 Ignoring builds in flakiness checks when ignore_flakiness is specified.
  app_dart/lib/src/request_handlers/check_flaky_builders.dart
  app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart
  app_dart/lib/src/request_handlers/flaky_handler_utils.dart
  app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart
  app_dart/test/request_handlers/check_flaky_builders_test_data.dart
  app_dart/test/request_handlers/file_flaky_issue_and_pr_test_data.dart
  app_dart/test/request_handlers/update_existing_flaky_issues_test_data.dart
Labels: waiting for tree to go green, autosubmit

#1835 Revert "[app_dart] Remove branches.txt"
  app_dart/README.md
  app_dart/dev/branches.txt
Labels: autosubmit

#1837 Adding ignoreFlakiness() to target.dart
  app_dart/lib/src/model/ci_yaml/target.dart
  app_dart/test/model/ci_yaml/target_test.dart
Labels: autosubmit

#1834 Catch exception to ack pub/sub message
  app_dart/lib/src/request_handlers/scheduler/request_subscription.dart
  app_dart/test/request_handlers/scheduler/request_subscription_test.dart
Labels: autosubmit

#1841 [dependabot] Remove human reviewers
  .github/dependabot.yml
Labels: autosubmit

#1847 Add models for auto-submit bot.
  auto_submit/lib/model/auto_submit_query_result.dart
  auto_submit/lib/model/auto_submit_query_result.g.dart
  auto_submit/pubspec.lock
  auto_submit/pubspec.yaml
  auto_submit/test/model/auto_submit_query_result_test.dart
Labels: autosubmit

#1838 Convert to using ciYaml.postsubmitTargets and Target.ignoreFlakiness()
  app_dart/lib/src/model/ci_yaml/target.dart
  app_dart/lib/src/request_handlers/check_flaky_builders.dart
  app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart
  app_dart/lib/src/request_handlers/update_existing_flaky_issues.dart
  app_dart/test/model/ci_yaml/target_test.dart
  app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart
Labels: autosubmit

#1848 Prevent multiple approvals.
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/lib/requests/github_webhook.dart
  auto_submit/lib/service/approver_service.dart
  auto_submit/test/requests/check_pull_request_test.dart
  auto_submit/test/utilities/mocks.dart
  auto_submit/test/utilities/mocks.mocks.dart
Labels: autosubmit

#1851 [device doctor] Use dart sdk beta to build
  .ci.yaml
  app_dart/integration_test/data/cocoon_config.json
  device_doctor/tool/build.sh
  device_doctor/tool/ensure_file
Labels: autosubmit

#1850 [app_dart] Remove package:pedantic
  app_dart/dev/deploy.dart
  app_dart/pubspec.lock
  app_dart/pubspec.yaml
Labels: autosubmit

#1856 [device doctor] Fix idevicediagnostics binary path for M1 bots
  device_doctor/lib/src/ios_device.dart
  device_doctor/test/src/ios_device_test.dart
Labels: autosubmit

#1855 wrapping AppBar.title in a Tooltip
  dashboard/lib/build_dashboard_page.dart
  dashboard/test/build_dashboard_page_test.dart
Labels: autosubmit

#1849 small hack to change favicon based on tree status.
  dashboard/web/favicon-failure.png
  dashboard/web/index.html
Labels: autosubmit

#1860 Pass properties on re-runs using the checkrun.
  app_dart/lib/src/service/luci_build_service.dart
  app_dart/test/src/service/fake_buildbucket.dart
Labels: autosubmit

#1854 Use models rather than json in auto submit app.
  auto_submit/build.yaml
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/test/requests/check_pull_request_test.dart
Labels: autosubmit

#1869 Fix null value in flakey test search.
  app_dart/lib/src/request_handlers/check_flaky_builders.dart
  app_dart/lib/src/request_handlers/file_flaky_issue_and_pr.dart
  app_dart/test/request_handlers/check_flaky_builders_test.dart
  app_dart/test/request_handlers/file_flaky_issue_and_pr_test.dart
Labels: waiting for tree to go green, autosubmit

#1879 [app_dart] branch creation: catch exceptions and provide better logging
  app_dart/lib/src/service/branch_service.dart
Labels: autosubmit

#1839 [ciyaml] add dimension support
  app_dart/lib/src/model/ci_yaml/target.dart
  app_dart/lib/src/model/proto/internal/scheduler.pb.dart
  app_dart/lib/src/model/proto/internal/scheduler.pbjson.dart
  app_dart/lib/src/model/proto/internal/scheduler.proto
  app_dart/test/model/ci_yaml/target_test.dart
  app_dart/test/src/utilities/entity_generators.dart
Labels: autosubmit

#1881 Prevent exceptions when the PR doesn't have any tests.
  auto_submit/lib/requests/check_pull_request.dart
Labels: autosubmit

#1878 [dashboard] Migrate to flutter_app_icon
  dashboard/lib/build_dashboard_page.dart
  dashboard/pubspec.lock
  dashboard/pubspec.yaml
  dashboard/web/index.html
Labels: autosubmit

#1884 remove package logging
  device_doctor/lib/src/android_device.dart
  device_doctor/lib/src/health.dart
  device_doctor/lib/src/ios_device.dart
  device_doctor/lib/src/utils.dart
  device_doctor/pubspec.lock
  device_doctor/pubspec.yaml
Labels: waiting for tree to go green

#1885 [dashboard] Update tree favicons
  auto_submit/test/requests/check_pull_request_test.dart
  dashboard/web/favicon-failure.png
  dashboard/web/favicon.png
Labels: autosubmit
