Repository flutter/cocoon, pull requests merged in 2022-04, with the labels that each got.

#1698 [scheduler] Process build messages with null task key
  app_dart/lib/src/request_handlers/postsubmit_luci_subscription.dart
  app_dart/lib/src/service/scheduler.dart
  app_dart/test/request_handlers/postsubmit_luci_subscription_test.dart
  app_dart/test/src/utilities/push_message.dart
Labels: waiting for tree to go green

#1697 [autosubmit] Control numbers of PR to be merged per cycle
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/test/requests/check_pull_request_test.dart
Labels: waiting for tree to go green

#1701 Revert "[app_flutter] wrap AppBar.title in a Tooltip"
  dashboard/lib/build_dashboard_page.dart
  dashboard/linux/flutter/CMakeLists.txt
  dashboard/pubspec.lock
  dashboard/test/build_dashboard_page_test.dart
Labels: waiting for tree to go green

#1700 [autosubmit] Fix create comment
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/lib/service/github_service.dart
  auto_submit/test/src/service/fake_github_service.dart
Labels: waiting for tree to go green

#1703 Pin cocoon main docker file version.
  Dockerfile
Labels: waiting for tree to go green

#1699 [autosubmit] Use graphQL to get actual authorAssociation
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/lib/requests/check_pull_request_queries.dart
  auto_submit/lib/requests/exceptions.dart
  auto_submit/lib/service/config.dart
  auto_submit/lib/service/github_service.dart
  auto_submit/test/requests/check_pull_request_test.dart
  auto_submit/test/requests/github_webhook_test_data.dart
  auto_submit/test/service/github_service_test.dart
  auto_submit/test/src/service/fake_config.dart
  auto_submit/test/src/service/fake_github_service.dart
  auto_submit/test/src/service/fake_graphql_client.dart
  auto_submit/test/utilities/mocks.dart
  auto_submit/test/utilities/mocks.mocks.dart
Labels: waiting for tree to go green

#1686 [autosubmit] Add installation to generate github token
  auto_submit/lib/service/config.dart
  auto_submit/lib/service/secrets.dart
  auto_submit/test/service/config_test.dart
  auto_submit/test/service/config_test_data.dart
Labels: waiting for tree to go green

#1704 [autosubmit] Fix graphQL Client
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/lib/requests/check_pull_request_queries.dart
  auto_submit/lib/service/config.dart
  auto_submit/test/requests/check_pull_request_test.dart
Labels: waiting for tree to go green, autosubmit

#1711 Increase label node request limit when graphql quering waiting PRs
  app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
  app_dart/lib/src/request_handlers/check_for_waiting_pull_requests_queries.dart
Labels: waiting for tree to go green

#1712 Do not run scorecards on forks.
  .github/workflows/mirror.yml
  .github/workflows/scorecards-analysis.yml
Labels: waiting for tree to go green

#1708 [autosubmit] Get correct installation id
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/lib/service/config.dart
  auto_submit/test/service/config_test.dart
  auto_submit/test/src/service/fake_config.dart
Labels: waiting for tree to go green

#1713 [app_dart] Add flutter-2.13-candidate.0 to release branches
  app_dart/dev/branches.txt
  app_dart/lib/src/service/config.dart
  app_dart/test/service/config_test.dart
Labels: waiting for tree to go green, autosubmit

#1706 Add platform-ios to iOS tool code
  app_dart/lib/src/request_handlers/github_webhook.dart
  app_dart/test/request_handlers/github_webhook_test.dart
Labels: waiting for tree to go green

#1714 [app_dart] Add branch support to get green commits
  app_dart/lib/src/request_handlers/get_green_commits.dart
  app_dart/test/request_handlers/get_green_commits_test.dart
Labels: waiting for tree to go green

#1715 [app_dart] Approve release PRs
  app_dart/lib/src/request_handlers/github_webhook.dart
  app_dart/lib/src/service/config.dart
  app_dart/test/request_handlers/github_webhook_test.dart
  app_dart/test/src/datastore/fake_config.dart
  app_dart/test/src/utilities/webhook_generators.dart
Labels: waiting for tree to go green

#1717 [autosubmit] Authenticate user
  auto_submit/bin/server.dart
  auto_submit/lib/foundation/typedefs.dart
  auto_submit/lib/request_handling/authentication.dart
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/lib/requests/github_webhook.dart
  auto_submit/lib/server/authenticated_request_handler.dart
  auto_submit/lib/server/exceptions.dart
  auto_submit/lib/server/request_handler.dart
  auto_submit/test/request_handling/authentication_test.dart
  auto_submit/test/requests/check_pull_request_test.dart
  auto_submit/test/src/request_handling/fake_authentication.dart
Labels: waiting for tree to go green

#1720 Refactor cronjob deploy to include auto-submit bot
  cloud_build/deploy_app_dart.sh
  cloud_build/deploy_cron_jobs.sh
  cloudbuild_cron.yaml
  cron.yaml
Labels: waiting for tree to go green

#1721 [autosubmit] Fix authentication
  auto_submit/bin/server.dart
  auto_submit/lib/server/authenticated_request_handler.dart
  auto_submit/lib/server/request_handler.dart
  auto_submit/lib/service/config.dart
  auto_submit/test/requests/check_pull_request_test.dart
Labels: waiting for tree to go green, autosubmit

#1719 [autosubmit] Add merge pull request
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/lib/service/github_service.dart
  auto_submit/test/requests/check_pull_request_test.dart
  auto_submit/test/requests/github_webhook_test_data.dart
  auto_submit/test/src/service/fake_github_service.dart
Labels: autosubmit

#1723 [autosubmit] Add after merge log
  auto_submit/lib/requests/check_pull_request.dart
Labels: autosubmit

#1724 [autosubmit] Add author association log
  auto_submit/lib/requests/check_pull_request.dart
Labels: autosubmit

#1725 [autosubmit] Add shouldmerge log
  auto_submit/lib/requests/check_pull_request.dart
Labels: autosubmit

#1722 [auto-submit] test merge pr permission
  auto_submit/lib/requests/check_pull_request.dart
Labels: autosubmit

#1726 [autosubmit] Add ack pubsub log
  auto_submit/lib/requests/check_pull_request.dart
Labels: autosubmit

#1728 [autosubmit] Add valid merge PR
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/lib/service/github_service.dart
  auto_submit/test/requests/check_pull_request_test.dart
  auto_submit/test/requests/github_webhook_test_data.dart
  auto_submit/test/src/service/fake_github_service.dart
Labels: autosubmit

#1730 [autosubmit] Auto update pull request branch
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/lib/service/github_service.dart
  auto_submit/test/requests/check_pull_request_test.dart
  auto_submit/test/requests/github_webhook_test_data.dart
  auto_submit/test/src/service/fake_github_service.dart
Labels: autosubmit

#1731 Add cpu dimension support when parsing ci yaml
  app_dart/lib/src/model/ci_yaml/target.dart
  app_dart/test/model/ci_yaml/target_test.dart
Labels: waiting for tree to go green

#1733 Add fuchsia_r48 to branches.txt
  app_dart/dev/branches.txt
Labels: waiting for tree to go green

#1736 Add dependabot for pub ecosystem.
  .github/dependabot.yml
Labels: waiting for tree to go green

#1735 [autosubmit] Add merge counts log
  auto_submit/lib/requests/check_pull_request.dart
Labels: autosubmit

#1734 [autosubmit] Add merge log
  auto_submit/lib/requests/check_pull_request.dart
Labels: autosubmit

#1738 [autosubmit] GraphQL merge PR
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/lib/requests/check_pull_request_queries.dart
  auto_submit/lib/service/github_service.dart
  auto_submit/test/requests/check_pull_request_test.dart
  auto_submit/test/src/service/fake_github_service.dart
Labels: waiting for tree to go green

#1729 [dashboard] Enable semantics
  dashboard/lib/main.dart
Labels: autosubmit

#1737 make devicelab tests count as tests
  app_dart/lib/src/request_handlers/github_webhook.dart
  app_dart/test/request_handlers/github_webhook_test.dart
Labels: waiting for tree to go green

#1741 [cron] Increase autosubmit frequency to 2 minutes
  cron.yaml
Labels: autosubmit

#1740 issue #102000, making cocoon dashboard task name filter case insensitive
  dashboard/lib/logic/task_grid_filter.dart
  dashboard/lib/widgets/filter_property_sheet.dart
  dashboard/test/logic/task_grid_filter_test.dart
Labels: autosubmit

#1742 [app_dart] Add remedy for ci.yaml validation failures by rebasing PR
  app_dart/lib/src/model/ci_yaml/ci_yaml.dart
Labels: autosubmit

#1743 Update modify mode when creating PRs via auto flake bot
  app_dart/lib/src/request_handlers/flaky_handler_utils.dart
Labels: autosubmit

#1747 Update dependabot pub configurations.
  .github/dependabot.yml
Labels: autosubmit

#1745 Support platform `mac_arm64_ios` when injecting devicelab xcode property
  app_dart/lib/src/model/ci_yaml/target.dart
Labels: autosubmit

#1744 Adding os filter to task grid filter.
  dashboard/analysis_options.yaml
  dashboard/lib/build_dashboard_page.dart
  dashboard/lib/logic/task_grid_filter.dart
  dashboard/test/goldens/build_dashboard.defaultPropertySheet.dark.png
  dashboard/test/goldens/build_dashboard.defaultPropertySheet.png
  dashboard/test/logic/task_grid_filter_test.dart
Labels: autosubmit

#1784 [autosubmit] Use PR author from graphQL query
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/lib/requests/check_pull_request_queries.dart
  auto_submit/test/requests/check_pull_request_test.dart
Labels: autosubmit

#1775 [device doctor] Migrate to null safety
  auto_submit/test/utilities/mocks.dart
  dashboard/pubspec.lock
  device_doctor/bin/main.dart
  device_doctor/lib/src/android_device.dart
  device_doctor/lib/src/device.dart
  device_doctor/lib/src/health.dart
  device_doctor/lib/src/host_utils.dart
  device_doctor/lib/src/ios_device.dart
  device_doctor/lib/src/mac.dart
  device_doctor/lib/src/utils.dart
  device_doctor/pubspec.lock
  device_doctor/pubspec.yaml
  device_doctor/test/src/android_device_test.dart
  device_doctor/test/src/fake_ios_device.dart
  device_doctor/test/src/health_test.dart
  device_doctor/test/src/host_utils_test.dart
  device_doctor/test/src/ios_device_test.dart
  device_doctor/test/src/mac_test.dart
  device_doctor/test/src/utils.dart
  device_doctor/test/src/utils_test.dart
  device_doctor/tool/build.bat
Labels: autosubmit

#1792 Remove mirroring to master.
  .github/workflows/mirror.yml
Labels: autosubmit

#1793 [app_dart] Add exe to postsubmit builds
  app_dart/lib/src/service/luci_build_service.dart
  app_dart/test/service/luci_build_service_test.dart
  app_dart/test/src/utilities/mocks.mocks.dart
Labels: autosubmit

#1794 Remove build repo_dashboard in deploy.dart
  app_dart/dev/deploy.dart
Labels: autosubmit

#1795 [test_utilities] Migrate pub to use dart pub
  test_utilities/bin/prepare_environment.sh
Labels: autosubmit

#1803 [auto submit]fix errors, pass tests
  auto_submit/analysis_options.yaml
  auto_submit/bin/server.dart
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/lib/requests/github_webhook.dart
  auto_submit/lib/server/request_handler.dart
  auto_submit/lib/service/config.dart
  auto_submit/pubspec.lock
  auto_submit/pubspec.yaml
  auto_submit/test/request_handling/authentication_test.dart
  auto_submit/test/requests/github_webhook_test.dart
  auto_submit/test/requests/github_webhook_test_data.dart
  auto_submit/test/service/config_test.dart
  auto_submit/test/src/request_handling/fake_pubsub.dart
  auto_submit/test/src/service/fake_github_service.dart
Labels: autosubmit

#1802 Fixes for auto-submit.
  auto_submit/lib/requests/check_pull_request.dart
  auto_submit/lib/requests/github_webhook.dart
  auto_submit/lib/service/approver_service.dart
  auto_submit/lib/service/config.dart
  auto_submit/test/service/approver_service_test.dart
  auto_submit/test/src/service/fake_config.dart
  auto_submit/test/utilities/mocks.dart
  auto_submit/test/utilities/mocks.mocks.dart
Labels: autosubmit

#1787 [dashboard] Fix ios and android filters
  README.md
  dashboard/lib/logic/task_grid_filter.dart
  dashboard/test/logic/task_grid_filter_test.dart
Labels: waiting for tree to go green, autosubmit

#1807 Use cocoon default branch when fetching GOB file
  app_dart/lib/src/foundation/utils.dart
  app_dart/test/foundation/utils_test.dart
Labels: autosubmit

#1805 [app_dart] Ignore latency check for TOT revert
  app_dart/lib/src/request_handlers/check_for_waiting_pull_requests.dart
  app_dart/test/request_handlers/check_for_waiting_pull_requests_test.dart
Labels: autosubmit
